### ISSUE TITLE
Ajouter le systeme de payement Paypal pour le renouvelement du compte user

### ISSUE THREAD

**Issue by jalilbengoufa** [ClubCedille/crabe-inventaire#24]

**Comment by notarock** [comment]
Est-ce que c'est fini ça? @jalilbengoufa 
Il y a le paiement lors de l'inscription, mais est-ce que c'est la meme choses ?

**Comment by jalilbengoufa** [comment]
ouais c'est la meme chose le paiement lors de l'inscription et le renouvelement. C'est fini, mais j'avais juste tester le happy path
