### ISSUE TITLE
Conception de tests unitaires

### ISSUE THREAD

**Issue by notarock** [ClubCedille/crabe-inventaire#30]
On en a pas! On ne peut donc pas prouver que le programme fonctionne.

**Comment by waldo121** [comment]
Cela semble venir par défaut avec la création du projet laravel. Il ne reste plus qu'à les coder. quand on fait des changements.

**Comment by waldo121** [comment]
Il y a 1 des deux tests de base qui plante à cause d'une redirection, je l'arrange pour qu'on ait un setup de tests qui roulent.
