### ISSUE TITLE
Gestion d'un produit , create , update, delete, backend

### ISSUE THREAD

**Issue by jalilbengoufa** [ClubCedille/crabe-inventaire#6]

**Comment by waldo121** [comment]
Côté Autorisation, qu'est-ce qu'on permet de faire à qui dans cette liste, mes hypothèse sont à droite:

- index(lister n'importe quel produit) // membre actuel
- show(voir un produit spécifique) // membre actuel
- create(montrer formulaire de création de produit) admin & membre actuel
- store(créer un nouveau produit) // admin & membre actuel
- edit(montrer la page pour modifier un produit) // admin & membre actuel
- update(maj un produit) // admin & membre actuel
- delete(supprimer un produit) // admin & membre actuel

Note: & -> Les 2 conditions doivent être respectées.

**Comment by jalilbengoufa** [comment]
index(lister n'importe quel produit) // membre actuel & admin
show(voir un produit spécifique) // membre actuel  & admin
create(montrer formulaire de création de produit) admin
edit(montrer la page pour modifier un produit) // admin 
update(maj un produit) // admin 
delete(supprimer un produit) // admin 

Je pense c'est plus comme ca, les membres peuvent seulment choisir un produit et voir tous ceux qui sont disponible.

**Comment by notarock** [comment]
Pour faire le suivi, le Backend est pas mal fait mais il manque le UI avec vue.js . Je pense que @elaforge98 avance là dessu, à confirmer

**Comment by notarock** [comment]
Pas trop d'avancement ici, je vais prendre la relève

**Comment by jalilbengoufa** [comment]
@notarock  j'ai pousse un docker-compose pour travailler sur le projet, ca va mieux qu'une vm https://github.com/ClubCedille/crabe-inventaire/blob/feature-42/docker-compose.yml

**Comment by notarock** [comment]
On pourrait le merger tout de suite sur develop si il fonctionne?

**Comment by jalilbengoufa** [comment]
oui

**Comment by waldo121** [comment]
> @notarock j'ai pousse un docker-compose pour travailler sur le projet, ca va mieux qu'une vm https://github.com/ClubCedille/crabe-inventaire/blob/feature-42/docker-compose.yml

Il y a une raison pour laquelle c'est rendu du mariadb?

**Comment by jalilbengoufa** [comment]
les deux sont compatible donc ca change rien, mais je peux le changer pour mettre mysql

**Comment by waldo121** [comment]
> On pourrait le merger tout de suite sur develop si il fonctionne?

On attend quelque chose pour merger ou ça ne fonctionne pas?

**Comment by notarock** [comment]
L'apparence est so-so meton, mais c'est fonctionnel

**Comment by waldo121** [comment]
Je pensais qu'on parlait du compose, mybad

**Comment by notarock** [comment]
> Je pensais qu'on parlait du compose, mybad

J'utilise vagrant/homestead et je trouve que ça va super, mais si tu veux le faire merger alors je vais review :+1:
